apiVersion: v1
kind: Service
metadata:
  name: minipunk-game
  namespace: game-system
spec:
  selector:
    app: minipunk-game
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP  # 클러스터 내부 통신용 