apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-backend
  namespace: game-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-backend
  template:
    metadata:
      labels:
        app: game-backend
    spec:
      containers:
      - name: game-backend
        image: 248189943688.dkr.ecr.us-east-2.amazonaws.com/game-backend:v0.0.5
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: redis-host
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: db-name
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: redis-port 