apiVersion: v1
kind: Service
metadata:
  name: game-backend
  namespace: game-system
spec:
  selector:
    app: game-backend
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP  # 클러스터 내부 통신용 