apiVersion: v1
kind: Service
metadata:
  name: game-backend
  namespace: game-system
spec:
  selector:
    app: game-backend
  ports:
  - name: http
    port: 80        # 이 부분이 ingress에서 사용하는 포트
    targetPort: 3000  # 컨테이너의 실제 포트
  type: ClusterIP  # 클러스터 내부 통신용 