apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-game
  namespace: game-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apple-game
  template:
    metadata:
      labels:
        app: apple-game
    spec:
      containers:
      - name: apple-game
        image: 248189943688.dkr.ecr.us-east-2.amazonaws.com/fruit-box:1.0
        ports:
        - containerPort: 80 