apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-website
  namespace: game-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-website
  template:
    metadata:
      labels:
        app: game-website
    spec:
      containers:
      - name: game-website
        image: <ECR_REGISTRY>/game-website:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 