apiVersion: v1
kind: Service
metadata:
  name: game-website
  namespace: game-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "application"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    kubernetes.io/ingress.class: alb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: game-website 