apiVersion: apps/v1
kind: Deployment
metadata:
  name: suika-game
  namespace: game-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suika-game
  template:
    metadata:
      labels:
        app: suika-game
    spec:
      containers:
      - name: suika-game
        image: 248189943688.dkr.ecr.us-east-2.amazonaws.com/suika-game:1.0
        ports:
        - containerPort: 80
        env:
        - name: NGINX_CORS
          value: "true"
        - name: NGINX_LOCATION
          value: "/public/"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 